[package]
name = "evonomics"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
iced = { git = "https://github.com/hecrj/iced", features = ["canvas", "tokio", "debug"] }
tokio = { version = "0.2", features = ["blocking"] }
itertools = "0.9"
rustc-hash = "1.1"
gridsim = "0.3.2"
rayon = "1.1.0"