[package]
name = "evonomics"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gridsim = "0.3.2"
gridsim-ui = "0.4.1"
rand = "0.7.3"
rand_distr = "0.2.2"
arrayvec = "0.5.1"
